---
name: Close stale issues and PRs

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub Actions Documentation
# https://docs.github.com/en/github-ae@latest/actions

on:
  # Run daily at 6:30 PM UTC
  schedule:
    - cron: '30 18 * * *'
  # or on button click
  workflow_dispatch:

jobs:
  close-stale:
    uses: rlaiola/ci-templates/.github/workflows/close-stale.yml@main
    # with:
    #   stale_issue_label: stale
    #   days_before_stale: 90
    #   days_before_pr_stale: 45
    #   days_before_close: 7
    #   days_before_pr_close: -1
    permissions:
      issues: write
      pull-requests: write
